

engine_main = "postgresql://90northbrands:90northbrands@34.41.36.17:5432/postgres"    

portals=['Myntra','Nykaa']

username="90northbrands"
password="90northbrands"



[connections.my_database]
    type="sql"
    dialect="postgresql"
    source_id="gold-braid-431812-g7"
    host="34.41.36.17" 
    port=5432
    database="postgres"
    username="90northbrands"
    password="90northbrands"
    

[passwords]
    90northbrands = "90northbrands"













    
