

engine_main = "postgresql://90northbrands:90northbrands@localhost:5432/90northbrands"    

portals=['Myntra','Nykaa']





[connections.my_database]
    type="sql"
    dialect="postgresql"
    host="pg-2faca55c-myntra-analytics.j.aivencloud.com" 
    port=10514
    database="defaultdb"
    username="avnadmin"
    password="AVNS_6jsRetox8aiDcNWDG7m"
    

[passwords]
    90northbrands = "90northbrands"

