engine_main = "postgres://avnadmin:AVNS_6jsRetox8aiDcNWDG7m@pg-2faca55c-myntra-analytics.j.aivencloud.com:10514/defaultdb?sslmode=require"    

portals=['Myntra','Nykaa']





[connections.my_database]
    type="sql"
    dialect="postgresql"
    host="pg-2faca55c-myntra-analytics.j.aivencloud.com" 
    port=10514
    database="defaultdb"
    username="avnadmin"
    password="AVNS_6jsRetox8aiDcNWDG7m"
    

[passwords]
    90northbrands = "90northbrands"

