engine_main = "postgresql://avnadmin:AVNS_xnvbdzUyrUgfh1nhDxU@pg-255370f9-myntra-analytics.k.aivencloud.com:10514/defaultdb?sslmode=require"    

portals=['Myntra','Nykaa']





[connections.my_database]
    type="sql"
    dialect="postgresql"
    host="pg-255370f9-myntra-analytics.k.aivencloud.com" 
    port=10514
    database="defaultdb"
    username="avnadmin"
    password="AVNS_xnvbdzUyrUgfh1nhDxU"
    

[passwords]
    90northbrands = "90northbrands"
