

engine_main = "postgresql://90northbrands:90northbrands@localhost:5432/90northbrands"    

portals=['Myntra','Nykaa']





[connections.my_database]
    type="sql"
    dialect="postgresql"
    host="localhost" 
    port=5432
    database="90northbrands"
    username="90northbrands"
    password="90northbrands"
    

[passwords]
    90northbrands = "90northbrands"

